#!/usr/bin/env bash
#This script displays 1 to 20 but in 4th,9th,17th add some extra information
i=1;while((i<=20));do echo "${i}";case $i in 4) echo "bad luck from China";; 9) echo "bad luck from Japan" ;; 17) echo "bad luck from Italy" ;; esac; ((++i));done
