#!/usr/bin/env bash
#This script display time until 12 hours and 59 minutes
Hour=0;while((Hour<=12));do echo "Hour: ${Hour}";minutes=1;while((minutes<=59));do echo "${minutes}";((++minutes));done;((++Hour));done
