#!/usr/bin/env bash
#This scripts display a list of currently running processes
#Display “all processes(except both session leaders and processes not associated with a terminal: -a” 
#Display “all processes: -A”
#Display “user-oriented:u” 
#Dispay “TTY:Lift the BSD-style "must have a tty" restriction, which is imposed upon the set of all processes when some BSD-style (without "-"):x”
#Display “ASCII art process hierarchy (forest):f”
ps -Auxf

