#!/usr/bin/env bash
#This scripts display To infinity and beyond indefinitely.
#In between each iteration of the loop, add a sleep 2
#note: press Ctrl-C to stop this loop
while true
do
    echo “To infinity and beyond”
    sleep 2
done
