#!/usr/bin/env bash
#This script displays:
#To infinity and beyond indefinitely
#with sleep 2 in between each iteration
#I am invincible!!! When receiving a SIGTERM signal
msg()
{
     echo "I am invincible!!!"
}
trap "msg" SIGTERM

while true;
do
  echo "To infinity and beyond"
  sleep 2
done
